/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.70
 * Generated at: 2021-10-21 07:28:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.dept;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class department_005fpop_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>학과 테이블 팝업</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("	.required {color:red;}\r\n");
      out.write("	table {width:400px;}\r\n");
      out.write("	table th {width:120px; text-align:left;}\r\n");
      out.write("	input[type=\"text\"] {width:300px;}\r\n");
      out.write("</style>\r\n");
      out.write("<script  src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("	$(document).ready(function(){\r\n");
      out.write("		\r\n");
      out.write("		var mode = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("		if (mode == \"insert\"){\r\n");
      out.write("			$(\"#insertData\").attr('disabled', false);\r\n");
      out.write("			$(\"#updateData\").attr('disabled', true);\r\n");
      out.write("			$(\"#deleteData\").attr('disabled', true);\r\n");
      out.write("		}else if (mode == \"update\"){\r\n");
      out.write("			$(\"#insertData\").attr('disabled', true);\r\n");
      out.write("			$(\"#updateData\").attr('disabled', false);\r\n");
      out.write("			$(\"#deleteData\").attr('disabled', false);			\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		$(\"#insertData\").click(function(){\r\n");
      out.write("			if(!validateForm()) return;\r\n");
      out.write("			if (confirm('등록을 진행할까요?')){\r\n");
      out.write("				$(\"#deptForm\").attr(\"action\", \"insertDepartment.h\");					\r\n");
      out.write("				$(\"#deptForm\").submit();\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		$(\"#updateData\").click(function(){\r\n");
      out.write("			if(!validateForm()) return;\r\n");
      out.write("			if (confirm('수정을 진행할까요?')){\r\n");
      out.write("				$(\"#deptForm\").attr(\"action\", \"updateDepartment.h\");			\r\n");
      out.write("				$(\"#deptForm\").submit();\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		$(\"#deleteData\").click(function(){\r\n");
      out.write("			//if(!validateForm()) return;\r\n");
      out.write("			if (confirm('삭제를 진행할까요?')){\r\n");
      out.write("				$(\"#deptForm\").attr(\"action\", \"deleteDepartment.h\");	\r\n");
      out.write("				$(\"#deptForm\").submit();\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		$(\"#closeWindow\").click(function(){\r\n");
      out.write("			window.close();\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	function validateForm() {\r\n");
      out.write("		 if($(\"#deptid\").val().replace(/\\s/g,\"\") == \"\") {\r\n");
      out.write("			 alert('학과코드를 입력해주세요.');\r\n");
      out.write("			 return false;\r\n");
      out.write("		 }\r\n");
      out.write("		 if($(\"#deptname\").val().replace(/\\s/g,\"\") == \"\") {\r\n");
      out.write("			 alert('학과명을 입력해주세요.');\r\n");
      out.write("			 return false;\r\n");
      out.write("		 }\r\n");
      out.write("		 return true;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<p></p>\r\n");
      out.write("<div>\r\n");
      out.write("<form id=\"deptForm\" name=\"deptForm\" method=\"GET\">\r\n");
      out.write("<table board=\"1\">\r\n");
      out.write("<thead>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<td colspan=\"2\" align=\"center\">\r\n");
      out.write("			<h4>학과 테이블 팝업창 [Spring]</h4>\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("</thead>\r\n");
      out.write("<tbody>	\r\n");
      out.write("	<tr>\r\n");
      out.write("		<th><span class=\"required\">*</span>학과코드</th>\r\n");
      out.write("		<td>\r\n");
      out.write("			<input type=\"text\" id=\"deptid\" name=\"deptid\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${DeptVO.deptid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<th><span class=\"required\">*</span>학과명</th>\r\n");
      out.write("		<td>\r\n");
      out.write("			<input type=\"text\" id=\"deptname\" name=\"deptname\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${DeptVO.deptname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	<tr>\r\n");
      out.write("		<th><span class=\"required\">*</span>전화번호</th>\r\n");
      out.write("		<td>\r\n");
      out.write("			<input type=\"text\" id=\"depttel\" name=\"depttel\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${DeptVO.depttel}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>	\r\n");
      out.write("</tbody>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("<div>\r\n");
      out.write("<p></p>\r\n");
      out.write("<table boarder=\"0\">\r\n");
      out.write("	<tr align=\"center\">\r\n");
      out.write("		<td><input type=\"button\" id=\"insertData\" value=\"등록\" /></td>\r\n");
      out.write("		<td><input type=\"button\" id=\"updateData\" value=\"수정\" /></td>\r\n");
      out.write("		<td><input type=\"button\" id=\"deleteData\" value=\"삭제\" /></td>\r\n");
      out.write("		<td><input type=\"button\" id=\"closeWindow\" value=\"닫기\" /></td>						\r\n");
      out.write("	</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
